<?php

namespace App\Models\Satis;

use App\Models\BaseModel;

use DB;

class Teklif extends BaseModel
{
    public $table = 'Teklifler';

    protected $fillable = [
        'id',
        'Nosu',
        'Tarih',
        'FirmaKodu',
        'VerenYetkili',
        'AlanYetkili',
        'MFiyatKodu',
        'MKdv',
        'Kapan',
        'Iptal',
        'Nakliye',
        'Odeme',
        'Teslim',
        'Aciklama',
        'IhracKayitli',
        'GecerliGun',
        'FirmaAdi',
        'SevkTarihi',
        'TeslimTarihi',
        'VadeGun',
        'Kampanyali',
        'KampanyaKodu',
        'VerenSicilNo',
        'AlanSicilNo',
        'SevkFirmaKod',
        'SevkFirmaAdi',
        'SevkAdres1',
        'SevkAdres2',
        'SevkAdres3',
        'il',
        'ilce',
        'Ulke',
        'Durum',
        'SAS_No',
        'VarisYeri',
        'OdemeTarihi',
        'SigortaTut',
        'NakliyeTut',
        'YICINakSig',
        'NSDovizKod',
        'SonYukleme',
        'TahsilatBilgisi',
        'DovizKod',
        'MIsk1',
        'MIsk2',
        'MIsk3',
        'TeslimBilgisi',
        'Ihracat',
        'Sirket_Kod',
        'MaliyetFiyKodu1',
        'MaliyetFiyKodu2',
        'm_SirketKod',
        'KdvSifir',
        'AsilCariKod',
        'AsilCariAdi',
        'SaticiKodu',
        'TeklifNo2',
        'KullKisaKodu',
        'KayitTarihi1',
        'KullaniciNo1',
        'KayitTarihi',
        'KullaniciNo',
        'Isk3Tutar',
        'PrimYuzde',
        'UretTerminTarihi',
        'UretIlkTermGelisi',
        'UretSonTermGelisi',
        'TerminAciklamasi',
        'UrunHazirOlmaTarihi',
        'FonYuzde',
        'IsTel',
        'CepTel',
        'FaturaAdi',
        'FaturaAdres1',
        'FaturaAdres2',
        'FaturaAdres3',
        'FaturaUlkeId',
        'FaturaIlId',
        'FaturaIlceId',
        'FaturaAdresId',
        'FaturaVergiDairesi',
        'FaturaVergiNo',
        'OdemeDurumu',
        'OdemeTaksitSayisi',
        'KomisyonYuzdesi',
        'KargoUcreti',
        'KapidaOdemeBedeli',
        'TahsilatTutari',
        'PotansiyelSId',
        'BolgeKod',
        'RefMasId',
        'IlkTeklifid',
        'RevNo',
        'PotansiyelCariId',
        'TeslimYeri',
        'FirmaTipi',
        'ProjeliSatis',
        'OdemeDiger',
        'DovizKuru',
        'SatirlariSeciliDovizeCevir',
        'SevkAdres4',
        'DizaynLogoKod',
        'Projeid',
        'FaturaCariKod',
        'IhracatBelliDegil',
        'Ozellik_1',
        'Ozellik_2',
        'IhracatTeslimYeri',
        'Taksitli',
        'TakipNo',
        'TransportModeCode'
    ];

    public function satirlar()
    {
        return $this->hasMany(TeklifSatir::class, 'Masterid', 'id');
    }
}
