<?php

namespace App\Models\Muhasebe;

use App\Models\BaseModel;

use DB;

class MCari extends BaseModel
{
    public $table = 'm_CariKart';

    protected $fillable = [
        'SirketKod',
        'id',
        'CariKod',
        'CariAdi',
        'CariHesapTipi',
        'KisaCariAdi',
        'KaraListe',
        'KaraListeAciklama',
        'GrupSirketiMi',
        'GrupSirketi',
        'KarsiSirketCariKod',
        'Adres1',
        'Adres2',
        'Adres3',
        'FatAdres1',
        'FatAdres2',
        'FatAdres3',
        'PostaKodu',
        'Ulke',
        'Sehir',
        'Ilce',
        'Tel1',
        'Tel2',
        'DahiliTelNo',
        'Fax',
        'EPosta',
        'WWWAdres',
        'AnaYetkiliAdi',
        'VergiDaire',
        'VergiNo',
        'SicilKod',
        'Sermaye',
        'KurulusTarihi',
        'HesapKod',
        'BankaKod',
        'BankaNo',
        'BankaSube',
        'SubeNo',
        'BankaHesap',
        'KrediKartNo',
        'KrediKartSonTarih',
        'IsoBelgesiVar',
        'BolgeKod',
        'OzelKod1',
        'OzelKod2',
        'DovizKod',
        'CokluDoviz',
        'SaticiKod',
        'Aciklama',
        'Aktif',
        'VadeGun',
        'VadeOpsiyon',
        'EskiCariKod',
        'YeniCariKod',
        'Isk1',
        'Isk2',
        'Isk3',
        'FiyatKodu',
        'GrupKod',
        'IBANNO',
        'Kdv',
        'Nakliye',
        'Odeme',
        'Teslim',
        'VarisYeri',
        'OdemeTarihi',
        'OzelKod3',
        'OzelKod4',
        'OzelKod5',
        'AcikHesapLimiti',
        'KayitTarihi',
        'KullaniciNo',
        'DegTarihi',
        'DegKullNo',
        'OzelKod6',
        'OzelKod7',
        'SevkMinLimit',
        'VergiNo_int',
        'YurtIciDisi',
        'Sektor',
        'FaturaEmail',
        'AHLdeAcikMusSipAL',
        'AHL_Uyari',
        'AHL_SevkEngelle',
        'AHL_SipEngelle',
        'CekLimiti',
        'SenetLimiti',
        'CekSenetLimiti',
        'SevkEmriEmail',
        'IrsaliyeEmail',
        'SatisIadeEmail',
        'KKOtelemeGunKendi',
        'KKOtelemeGunBaska',
        'KKOtelemeGunYDisi',
        'EFaturaProfileIDType',
        'TICARETSICILNO',
        'MERSISNO',
        'SahisAdi1',
        'SahisAdi2',
        'SahisSoyadi',
        'WEBeEkstreGonder',
        'GrupTanimi',
        'MutabakatMail',
        'Sevkil',
        'Sevkilce',
        'SevkUlke',
        'OzelKod8',
        'BankalardakiKrediLimiti',
        'BankalardakiGayriKrediLimiti',
        'BankalardakiNakdiRiski',
        'BankalardakiGayriNakdiRiski',
        'TahsildekiKendiCeki',
        'YazilmisCekiVar',
        'YazilmisCekTutari',
        'ToplamOdedigiCekTutari',
        'TC_Seriii',
        'TC_SeriNo',
        'TC_DogumYeri',
        'TC_DogumTarihi',
        'TC_MedeniHali',
        'TC_CiltNo',
        'TC_AileSiraNo',
        'TC_SiraNo',
        'FiyatKoduIleAlacakTakibi',
        'SektorAgirligi',
        'SektordeYaptigiIs',
        'Kaynakid',
        'KaynakProg',
        'KurFarkiHesaplama',
        'Adres4',
        'FatAdres4',
        'IletisimDurumu'
    ];

    public function ozel_fiyatlandirma_listesi()
    {
        // Sirket_Kod eklenecek?
        return $this->hasMany(MCariOzelFiyat::class, 'CariKod', 'CariKod');
    }
}
